version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
networks:
  default:
    name: test
    external: true
